export interface GuideSection {
  title: string
  body: string
  source: string
}

export const guideContent: Record<string, GuideSection> = {
  landing: {
    title: 'The Conversion Funnel',
    body: 'The landing page is designed as a conversion funnel. The headline hooks with a challenge ("Prove you can trade"), the stats build credibility, the dashboard preview shows what\'s inside, and the CTA offers something concrete ($100K in simulated capital). The target: 70%+ of visitors start the quiz, 85%+ of profile reveals convert to account creation.',
    source: 'Source: Tech Stack & User Flow Doc, Section 12 - Conversion Funnel Strategy',
  },
  onboarding: {
    title: 'Value Before Account Creation',
    body: 'The quiz delivers value before asking for signup. Every screen is a single tap, no text fields. By the profile reveal, the user owns something (their Trading DNA) that they don\'t want to lose. Total time: under 60 seconds. Target: 90%+ quiz completion rate, 85%+ conversion from reveal to signup.',
    source: 'Source: Tech Stack & User Flow Doc, Section 9 - User Flow: Onboarding',
  },
  discover: {
    title: 'The Daily Loop',
    body: 'Discover is the home screen and the start of the daily trading loop. Portfolio value, positions, and recent activity give the trader their morning briefing. Trending tickers (powered by live Finnhub data) surface what the community is watching. The floating trade button provides instant access to execution. Everything here updates in real time as trades are made.',
    source: 'Source: Tech Stack & User Flow Doc, Section 10 - Core Trading Loop',
  },
  trade: {
    title: 'The Rules Engine',
    body: 'Every trade is validated in real time against the rules engine before execution. These constraints filter for process over luck. You can\'t YOLO your way to the top. You have to actually be good.',
    source: 'Source: Pitch Deck, "The Rules Engine" slide',
  },
  room: {
    title: 'The Room: Transparent Social Trading',
    body: 'The Room is where traders post public theses with conviction scores. Every position and track record is transparent. In production, the AI Signal Scorer (Claude API) evaluates each thesis against ETF flows, options data, and earnings revisions. The best theses surface through quality, not followers. Community features require multiple users and are shown here as a preview.',
    source: 'Source: Friends & Family Deck, "The Product" - The Room; Technical Architecture Doc, Section 7 - AI Signal Scoring',
  },
  predict: {
    title: 'Prediction Markets',
    body: 'Community-driven prediction markets on market events. Users stake reputation (not capital) on binary outcomes. Prediction accuracy feeds into the leaderboard algorithm and Trading DNA profile. This feature requires community participation and is shown as a preview.',
    source: 'Source: Technical Architecture Doc, Section 6 - Gamification',
  },
  board: {
    title: 'The Leaderboard',
    body: 'Rankings use a composite score: 40% risk-adjusted returns, 25% thesis quality, 20% consistency, 15% community score. Time-weighting ensures longevity matters: traders with 2+ years of consistent returns outrank 3-month hot streaks. Desk-specific leaderboards (Tech Desk, Healthcare Desk, etc.) allow sector specialists to compete fairly. The qualification path runs from Rookie through Contender, Strategist, and Expert to Fund-Ready.',
    source: 'Source: Technical Architecture Doc, Section 9.2 - Skill vs. Luck Decomposition; Pitch Deck, "The Leaderboard" slide',
  },
  mirror: {
    title: 'AI Trading DNA Profiler',
    body: 'The Mirror uses Claude (Anthropic\'s AI) to analyze every trade, position, and timing decision. It identifies dominant patterns, generates a natural-language strategy profile, and scores 8 behavioral traits. The profile evolves as trading behavior changes. This is Yabo\'s core differentiator: no competitor in the market offers AI-driven behavioral profiling of trading activity.',
    source: 'Source: Pitch Deck, "AI Strategy Profiler" slide; Technical Architecture Doc, Section 5 - AI/ML Pipeline',
  },
  strategy: {
    title: 'AI-Powered Recommendations',
    body: 'Strategy recommendations are generated by Claude API based on the trader\'s complete behavioral profile and current portfolio state. Recommendations reference specific positions and patterns, not generic advice. Priority levels (high/medium/low) help traders focus on what matters most. In production, recommendations update after every trade.',
    source: 'Source: Technical Architecture Doc, Section 5.4 - Recommendation Generation Pipeline',
  },
  moves: {
    title: 'The Move: Collective Buying Power',
    body: 'When the community has conviction and the AI validates a thesis, users can opt into coordinated positions. 5,000 people at $5K each equals $25M of directed, intelligent capital. This is institutional-scale impact from retail participants. Moves require validated theses, minimum participant thresholds, and pass through the Circuit Breaker system to prevent herd behavior.',
    source: 'Source: Friends & Family Deck, "The Product" - The Move; Technical Architecture Doc, Section 9.1 - Circuit Breaker System',
  },
  import: {
    title: 'Trade History Import',
    body: 'Users can import existing trade history from any brokerage via CSV. The import engine parses trades, calculates positions, recalculates portfolio value, and triggers Claude AI analysis to generate their Trading DNA profile. This means a trader with years of history can get their behavioral profile on day one, without re-executing trades on the platform.',
    source: 'Source: Tech Stack & User Flow Doc, Section 10 - Core Trading Loop',
  },
}

export const discoverStats = [
  'Starting capital: $100,000',
  'Positions tracked in Supabase (PostgreSQL)',
  'Prices from Finnhub API (real-time US equities)',
  'Portfolio recalculated after every trade',
]

export const rulesTableData = [
  { rule: 'Max Single Position', constraint: '15% of portfolio', status: 'active' as const },
  { rule: 'Minimum Positions', constraint: '5 positions at all times', status: 'warning' as const },
  { rule: 'Deployment Minimum', constraint: '70% must be deployed', status: 'warning' as const },
  { rule: 'Max Drawdown', constraint: '30% triggers cooldown', status: 'active' as const },
  { rule: 'Sector Limit', constraint: '40% max in one sector', status: 'active' as const },
  { rule: 'Options Cap', constraint: '30% notional value', status: 'future' as const },
]

export const tradeNote = 'Trades include simulated slippage (0.02%) and commission modeling ($0.01/share, $0.50 minimum) for realistic execution.'

export const tierTableData = [
  { tier: 'Rookie', requirements: 'Starting tier. Complete onboarding.' },
  { tier: 'Contender', requirements: '50+ trades, 3+ months active' },
  { tier: 'Strategist', requirements: 'Top 25% composite score, 6+ months' },
  { tier: 'Expert', requirements: 'Top 10%, 12+ months, positive alpha' },
  { tier: 'Fund-Ready', requirements: 'Top 5%, 12+ months, passes skill vs. luck test' },
]

export const mirrorAnalysisList = [
  'Entry/exit timing patterns',
  'Position sizing behavior',
  'Sector concentration tendencies',
  'Loss-cutting discipline',
  'Conviction accuracy (do high-conviction trades perform better?)',
  'Behavioral changes over time',
  'Stress response under drawdowns',
]

export const whatsNextPhases = [
  {
    title: 'Phase 2: The Arena',
    timeline: 'Months 4-9',
    items: [
      'Seasonal competitions (Earnings Season Challenge, Black Swan Challenge)',
      'Follow/watch system with delayed trade feeds',
      'Advanced leaderboards with desk-specific rankings',
      'Limit orders, stop-loss, stop-limit order types',
      'Options trading (calls, puts, multi-leg strategies)',
      'Real-time price streaming via WebSocket',
      'Push notifications',
    ],
  },
  {
    title: 'Phase 3: The Fund',
    timeline: 'Months 8-12+',
    items: [
      'Qualification pipeline (Rookie to Fund-Ready)',
      'Legal entity and compliance setup',
      'Real-money brokerage integration',
      'Commission and payout system',
      'External LP onboarding',
      'KYC/AML verification at Fund-Ready tier',
    ],
  },
]
