import { Trader, Thesis, StrategyRecommendation, BehavioralTrait, CollectiveMove } from "@/types";

export const traders: Trader[] = [
  {
    id: 1,
    name: "MarketOwl",
    dna: "Momentum Rider",
    winRate: 0.72,
    sharpe: 2.1,
    rep: 4820,
    rank: 1,
    initials: "MO",
    streak: 7,
    level: 42,
    xp: 8400,
    tier: "Elite",
  },
  {
    id: 2,
    name: "ThetaGang_Mike",
    dna: "Premium Collector",
    winRate: 0.81,
    sharpe: 1.8,
    rep: 4350,
    rank: 2,
    initials: "TM",
    streak: 12,
    level: 38,
    xp: 7600,
    tier: "Elite",
  },
  {
    id: 3,
    name: "DeepValue_Sarah",
    dna: "Disciplined Contrarian",
    winRate: 0.68,
    sharpe: 2.4,
    rep: 3980,
    rank: 3,
    initials: "DS",
    streak: 4,
    level: 35,
    xp: 7000,
    tier: "Fund-Ready",
  },
  {
    id: 4,
    name: "ChipTrader",
    dna: "Sector Specialist",
    winRate: 0.74,
    sharpe: 1.9,
    rep: 3640,
    rank: 4,
    initials: "CT",
    streak: 5,
    level: 31,
    xp: 6200,
    tier: "Fund-Ready",
  },
  {
    id: 5,
    name: "SwingKing_J",
    dna: "Patient Holder",
    winRate: 0.66,
    sharpe: 1.7,
    rep: 3210,
    rank: 5,
    initials: "SJ",
    streak: 3,
    level: 28,
    xp: 5600,
    tier: "All-Star",
  },
  {
    id: 6,
    name: "VolSurfer",
    dna: "Volatility Harvester",
    winRate: 0.77,
    sharpe: 2.0,
    rep: 2980,
    rank: 6,
    initials: "VS",
    streak: 6,
    level: 26,
    xp: 5200,
    tier: "All-Star",
  },
  {
    id: 7,
    name: "Macro_Dan",
    dna: "Sector Rotator",
    winRate: 0.63,
    sharpe: 2.2,
    rep: 2740,
    rank: 7,
    initials: "MD",
    streak: 2,
    level: 24,
    xp: 4800,
    tier: "All-Star",
  },
  {
    id: 8,
    name: "EarningsWhisperer",
    dna: "Earnings Player",
    winRate: 0.71,
    sharpe: 1.6,
    rep: 2510,
    rank: 8,
    initials: "EW",
    streak: 4,
    level: 21,
    xp: 4200,
    tier: "Contender",
  },
];

export const theses: Thesis[] = [
  {
    id: 1,
    trader: traders[0],
    ticker: "NVDA",
    direction: "long",
    price: 142.5,
    target: 165,
    stop: 128,
    conviction: 87,
    signal: 82,
    tqs: 78,
    text: "Blackwell ramp is being underestimated. Hyperscaler capex guides all pointing up 30%+ YoY. Supply constraints easing Q2. PT $165 based on 35x CY26 EPS of $4.70.",
    timeAgo: "12m",
    replies: 24,
    repCount: 182,
    chartData: [42, 44, 43, 46, 48, 47, 50, 52, 51, 54, 56, 55, 58, 60, 62],
    yesVotes: 147,
    noVotes: 23,
    expiresIn: "14d",
    probability: 0.78,
  },
  {
    id: 2,
    trader: traders[2],
    ticker: "COST",
    direction: "long",
    price: 985,
    target: 1080,
    stop: 940,
    conviction: 74,
    signal: 71,
    tqs: 85,
    text: "Membership renewal rates at all-time high of 93.4%. E-commerce growing 20%+ while legacy retail contracts. Sticky consumer base + pricing power = compounder.",
    timeAgo: "1h",
    replies: 18,
    repCount: 94,
    chartData: [80, 82, 81, 83, 85, 84, 86, 85, 87, 88, 87, 89, 90, 91, 92],
    yesVotes: 89,
    noVotes: 31,
    expiresIn: "21d",
    probability: 0.71,
  },
  {
    id: 3,
    trader: traders[1],
    ticker: "AMZN",
    direction: "long",
    price: 228,
    target: 255,
    stop: 215,
    conviction: 91,
    signal: 88,
    tqs: 82,
    text: "AWS re-acceleration to 19% growth not priced in. Advertising hitting $60B run rate. Selling Mar 260 calls at $4.20 while IV rank 78th percentile.",
    timeAgo: "2h",
    replies: 31,
    repCount: 215,
    chartData: [60, 62, 61, 63, 65, 64, 67, 69, 68, 71, 73, 72, 74, 76, 78],
    yesVotes: 198,
    noVotes: 17,
    expiresIn: "28d",
    probability: 0.85,
  },
  {
    id: 4,
    trader: traders[3],
    ticker: "AVGO",
    direction: "long",
    price: 238,
    target: 275,
    stop: 218,
    conviction: 82,
    signal: 76,
    tqs: 73,
    text: "Custom ASIC business inflecting. VMware integration ahead of schedule. Networking portfolio for AI cluster buildout. R/R compelling at 22x forward.",
    timeAgo: "3h",
    replies: 12,
    repCount: 67,
    chartData: [50, 51, 53, 52, 54, 56, 55, 57, 59, 58, 60, 62, 61, 63, 65],
    yesVotes: 72,
    noVotes: 28,
    expiresIn: "18d",
    probability: 0.68,
  },
];

export const strategyRecommendations: StrategyRecommendation[] = [
  {
    ticker: "NVDA",
    action: "Write Covered Call",
    urgency: "high",
    narrative:
      "NVDA up 22% in 3 weeks. March $155 calls at $8.40 premium. If called: 31% total return. If not: 5.9% income on position.",
    behavioral:
      "You hold winners past optimal exit 73% of the time. Monetize via premium.",
    impact: 2340,
  },
  {
    ticker: "AMD",
    action: "Define Exit",
    urgency: "medium",
    narrative:
      "Position up 14% with no stop or target. Historical: you hold AMD positions avg 34 days, optimal exit is day 21. Define $185 target.",
    behavioral:
      "Positions without predefined exits underperform your average by 340bps.",
    impact: 1830,
  },
  {
    ticker: "COST",
    action: "Tax-Loss Pair",
    urgency: "low",
    narrative:
      "COST down 3.2%. TGT shares down 11% -- harvest TGT loss, rotate to COST for similar consumer exposure. Net tax benefit at your bracket: $1,100.",
    behavioral:
      "Tax harvesting opportunities identified in 4 of your positions.",
    impact: 1100,
  },
];

export const behavioralTraits: BehavioralTrait[] = [
  { name: "Stock Selection", score: 82, percentile: 91, trend: "up" },
  { name: "Entry Timing", score: 78, percentile: 84, trend: "up" },
  { name: "Exit Discipline", score: 54, percentile: 38, trend: "down" },
  { name: "Position Sizing", score: 71, percentile: 67, trend: "flat" },
  { name: "Sector Allocation", score: 88, percentile: 96, trend: "up" },
  { name: "Risk Management", score: 65, percentile: 52, trend: "flat" },
];

export const collectiveMoves: CollectiveMove[] = [
  {
    id: 1,
    ticker: "NVDA",
    direction: "long",
    signal: 82,
    catalyst:
      "Blackwell GPU shipments ramping faster than expected. Multiple hyperscalers increasing capex guidance. Datacenter revenue expected to exceed $30B next quarter.",
    conviction: 82,
    participants: 847,
    target: 165,
    currentPrice: 142.5,
  },
  {
    id: 2,
    ticker: "META",
    direction: "long",
    signal: 74,
    catalyst:
      "AI-driven ad targeting improvements driving 20%+ revenue growth. Reality Labs losses narrowing. WhatsApp monetization inflecting with business messaging.",
    conviction: 74,
    participants: 412,
    target: 640,
    currentPrice: 582,
  },
];

export const currentUser: Trader = traders[3]; // ChipTrader
