export const SECTOR_MAP: Record<string, string> = {
  // Technology - Semiconductors
  NVDA: "Semiconductors",
  AMD: "Semiconductors",
  INTC: "Semiconductors",
  AVGO: "Semiconductors",
  QCOM: "Semiconductors",
  MU: "Semiconductors",
  MRVL: "Semiconductors",
  TSM: "Semiconductors",
  ASML: "Semiconductors",
  LRCX: "Semiconductors",
  AMAT: "Semiconductors",
  KLAC: "Semiconductors",
  TXN: "Semiconductors",
  ON: "Semiconductors",
  ARM: "Semiconductors",
  SMCI: "Semiconductors",

  // Technology - Software
  MSFT: "Software",
  ORCL: "Software",
  CRM: "Software",
  ADBE: "Software",
  NOW: "Software",
  SNOW: "Software",
  PLTR: "Software",
  DDOG: "Software",
  NET: "Software",
  MDB: "Software",
  ZS: "Software",
  CRWD: "Software",
  PANW: "Software",

  // Technology - Internet/Cloud
  GOOGL: "Internet",
  GOOG: "Internet",
  META: "Internet",
  AMZN: "Internet",
  NFLX: "Internet",
  SNAP: "Internet",
  PINS: "Internet",
  SPOT: "Internet",
  UBER: "Internet",
  LYFT: "Internet",
  ABNB: "Internet",
  DASH: "Internet",
  SHOP: "Internet",

  // Technology - Hardware
  AAPL: "Hardware",
  DELL: "Hardware",
  HPQ: "Hardware",
  HPE: "Hardware",

  // Electric Vehicles
  TSLA: "EV",
  RIVN: "EV",
  LCID: "EV",
  NIO: "EV",
  LI: "EV",
  XPEV: "EV",

  // Financials
  JPM: "Financials",
  BAC: "Financials",
  WFC: "Financials",
  GS: "Financials",
  MS: "Financials",
  C: "Financials",
  BRK: "Financials",
  "BRK.B": "Financials",
  "BRK.A": "Financials",
  V: "Financials",
  MA: "Financials",
  AXP: "Financials",
  SCHW: "Financials",
  BLK: "Financials",
  COIN: "Financials",

  // Healthcare
  UNH: "Healthcare",
  JNJ: "Healthcare",
  PFE: "Healthcare",
  ABBV: "Healthcare",
  MRK: "Healthcare",
  LLY: "Healthcare",
  TMO: "Healthcare",
  ABT: "Healthcare",
  BMY: "Healthcare",
  AMGN: "Healthcare",
  GILD: "Healthcare",
  MRNA: "Healthcare",
  ISRG: "Healthcare",

  // Consumer
  COST: "Consumer",
  WMT: "Consumer",
  TGT: "Consumer",
  HD: "Consumer",
  LOW: "Consumer",
  NKE: "Consumer",
  SBUX: "Consumer",
  MCD: "Consumer",
  KO: "Consumer",
  PEP: "Consumer",
  PG: "Consumer",
  DIS: "Consumer",

  // Energy
  XOM: "Energy",
  CVX: "Energy",
  COP: "Energy",
  SLB: "Energy",
  EOG: "Energy",
  OXY: "Energy",
  DVN: "Energy",
  MPC: "Energy",
  PSX: "Energy",
  VLO: "Energy",

  // Industrials
  CAT: "Industrials",
  DE: "Industrials",
  BA: "Industrials",
  RTX: "Industrials",
  LMT: "Industrials",
  GE: "Industrials",
  HON: "Industrials",
  UPS: "Industrials",
  FDX: "Industrials",
  UNP: "Industrials",

  // ETFs
  SPY: "ETF",
  QQQ: "ETF",
  IWM: "ETF",
  DIA: "ETF",
  VTI: "ETF",
  VOO: "ETF",
  ARKK: "ETF",
  XLF: "ETF",
  XLE: "ETF",
  XLK: "ETF",
  SMH: "ETF",
  SOXX: "ETF",
  SOXL: "ETF",
  TQQQ: "ETF",
  SQQQ: "ETF",
};

export function getSector(ticker: string): string {
  const upper = ticker.toUpperCase().trim();
  return SECTOR_MAP[upper] || "Other";
}
