"""Feature schema: full list of 212 features with metadata."""

from __future__ import annotations

FEATURE_SCHEMA: list[dict] = [
    # ─── f01: Timing Behavior (18) ──────────────────────────────────────
    {"name": "timing_time_of_day_mode", "dimension": "timing", "type": "int", "description": "Hour (9-16) with most trades"},
    {"name": "timing_time_of_day_entropy", "dimension": "timing", "type": "float", "description": "Shannon entropy of hourly trade distribution"},
    {"name": "timing_morning_score", "dimension": "timing", "type": "float", "description": "Percentage of trades placed 9:30-10:30"},
    {"name": "timing_lunch_score", "dimension": "timing", "type": "float", "description": "Percentage of trades placed 11:30-13:00"},
    {"name": "timing_close_score", "dimension": "timing", "type": "float", "description": "Percentage of trades placed 14:30-16:00"},
    {"name": "timing_day_of_week_mode", "dimension": "timing", "type": "int", "description": "Most active weekday (0=Mon, 4=Fri)"},
    {"name": "timing_monday_ratio", "dimension": "timing", "type": "float", "description": "Monday trades / average daily trades"},
    {"name": "timing_friday_ratio", "dimension": "timing", "type": "float", "description": "Friday trades / average daily trades"},
    {"name": "timing_avg_trades_per_active_day", "dimension": "timing", "type": "float", "description": "Average trades on days with activity"},
    {"name": "timing_trading_days_per_month", "dimension": "timing", "type": "float", "description": "Average unique trading days per month"},
    {"name": "timing_longest_inactive_streak", "dimension": "timing", "type": "int", "description": "Max calendar days with no trades"},
    {"name": "timing_avg_inactive_gap", "dimension": "timing", "type": "float", "description": "Mean gap (days) between trading days"},
    {"name": "timing_gap_volatility", "dimension": "timing", "type": "float", "description": "Coefficient of variation of inter-trade gaps"},
    {"name": "timing_frequency_trend", "dimension": "timing", "type": "float", "description": "Slope of trades-per-month over time"},
    {"name": "timing_first_week_bias", "dimension": "timing", "type": "float", "description": "Percentage of trades in days 1-7 of month"},
    {"name": "timing_end_of_quarter_spike", "dimension": "timing", "type": "float", "description": "Activity in last 2 weeks of quarter vs normal"},
    {"name": "timing_december_shift", "dimension": "timing", "type": "float", "description": "December activity / average monthly activity"},
    {"name": "timing_january_shift", "dimension": "timing", "type": "float", "description": "January activity / average monthly activity"},

    # ─── f02: Position Sizing (16) ──────────────────────────────────────
    {"name": "sizing_avg_position_pct", "dimension": "sizing", "type": "float", "description": "Average trade value / estimated portfolio value"},
    {"name": "sizing_median_usd", "dimension": "sizing", "type": "float", "description": "Median trade dollar value"},
    {"name": "sizing_cv", "dimension": "sizing", "type": "float", "description": "Coefficient of variation of trade values"},
    {"name": "sizing_max_single_trade_pct", "dimension": "sizing", "type": "float", "description": "Largest single trade value / median portfolio value"},
    {"name": "sizing_min_usd", "dimension": "sizing", "type": "float", "description": "Smallest trade dollar value"},
    {"name": "sizing_round_number_bias", "dimension": "sizing", "type": "float", "description": "Percentage of share counts that are round numbers"},
    {"name": "sizing_fractional_usage", "dimension": "sizing", "type": "float", "description": "Percentage of trades with fractional shares"},
    {"name": "sizing_trend", "dimension": "sizing", "type": "float", "description": "Slope of trade sizes over time"},
    {"name": "sizing_after_wins", "dimension": "sizing", "type": "float", "description": "Average size after winning close / overall average"},
    {"name": "sizing_after_losses", "dimension": "sizing", "type": "float", "description": "Average size after losing close / overall average"},
    {"name": "sizing_largest_relative", "dimension": "sizing", "type": "float", "description": "Max trade value / median trade value"},
    {"name": "sizing_dca_score", "dimension": "sizing", "type": "float", "description": "CV of buy amounts for multi-buy positions (low = DCA)"},
    {"name": "sizing_conviction_ratio", "dimension": "sizing", "type": "float", "description": "For repeat tickers, max buy / min buy"},
    {"name": "sizing_new_ticker_ratio", "dimension": "sizing", "type": "float", "description": "Average size on first buy of ticker / overall average"},
    {"name": "sizing_cash_redeployment_days", "dimension": "sizing", "type": "float", "description": "Median days between a sell and next buy"},
    {"name": "sizing_max_accumulated_position_pct", "dimension": "sizing", "type": "float", "description": "Peak accumulated open-position value / median portfolio value"},

    # ─── f03: Holding Period (14) ───────────────────────────────────────
    {"name": "holding_median_days", "dimension": "holding", "type": "float", "description": "Median hold duration across closed positions"},
    {"name": "holding_avg_days", "dimension": "holding", "type": "float", "description": "Mean hold duration"},
    {"name": "holding_cv", "dimension": "holding", "type": "float", "description": "Consistency of hold periods (CV)"},
    {"name": "holding_pct_day_trades", "dimension": "holding", "type": "float", "description": "Percentage held less than 1 day"},
    {"name": "holding_pct_swing", "dimension": "holding", "type": "float", "description": "Percentage held 2-10 days"},
    {"name": "holding_pct_position", "dimension": "holding", "type": "float", "description": "Percentage held 10-60 days"},
    {"name": "holding_pct_investment", "dimension": "holding", "type": "float", "description": "Percentage held 60+ days"},
    {"name": "holding_shortest_hours", "dimension": "holding", "type": "float", "description": "Fastest round trip in hours"},
    {"name": "holding_longest_days", "dimension": "holding", "type": "float", "description": "Longest hold duration in days"},
    {"name": "holding_duration_trend", "dimension": "holding", "type": "float", "description": "Slope of hold durations over time"},
    {"name": "holding_disposition_ratio", "dimension": "holding", "type": "float", "description": "Median hold on losers / median hold on winners"},
    {"name": "holding_round_gain_exits", "dimension": "holding", "type": "float", "description": "Percentage of exits near round gain thresholds"},
    {"name": "holding_round_loss_exits", "dimension": "holding", "type": "float", "description": "Percentage of exits near round loss thresholds"},
    {"name": "holding_partial_close_rate", "dimension": "holding", "type": "float", "description": "Percentage of closes that are partial"},

    # ─── f04: Entry Behavior (16) ───────────────────────────────────────
    {"name": "entry_limit_ratio", "dimension": "entry", "type": "float", "description": "Percentage of buys that are limit orders"},
    {"name": "entry_vs_20d_high", "dimension": "entry", "type": "float", "description": "Average (entry price / 20-day high) across buys"},
    {"name": "entry_vs_52w_range", "dimension": "entry", "type": "float", "description": "Average position in 52-week range at entry (0=low, 1=high)"},
    {"name": "entry_dip_buyer_score", "dimension": "entry", "type": "float", "description": "Percentage of buys when stock down 5%+ from 20d high"},
    {"name": "entry_breakout_score", "dimension": "entry", "type": "float", "description": "Percentage of buys within 2% of 20-day high"},
    {"name": "entry_above_ma_score", "dimension": "entry", "type": "float", "description": "Percentage of buys above 20-day MA"},
    {"name": "entry_below_ma_score", "dimension": "entry", "type": "float", "description": "Percentage of buys below 20-day MA"},
    {"name": "entry_on_red_days", "dimension": "entry", "type": "float", "description": "Percentage of buys on days stock closed red"},
    {"name": "entry_on_green_days", "dimension": "entry", "type": "float", "description": "Percentage of buys on days stock closed green"},
    {"name": "entry_volume_relative", "dimension": "entry", "type": "float", "description": "Average relative volume on buy days"},
    {"name": "entry_buildup_days", "dimension": "entry", "type": "float", "description": "Average days from first to last buy for multi-buy positions"},
    {"name": "entry_gap_score", "dimension": "entry", "type": "float", "description": "Percentage of buys after overnight gap > 2%"},
    {"name": "entry_earnings_proximity", "dimension": "entry", "type": "float", "description": "Percentage of buys within 5 trading days of likely earnings"},
    {"name": "entry_pre_earnings", "dimension": "entry", "type": "float", "description": "Buys in 5 days before likely earnings / total"},
    {"name": "entry_post_earnings", "dimension": "entry", "type": "float", "description": "Buys in 5 days after likely earnings / total"},
    {"name": "entry_sector_rotation_speed", "dimension": "entry", "type": "float", "description": "Average days between selling one sector and buying another"},

    # ─── f05: Exit Behavior (16) ────────────────────────────────────────
    {"name": "exit_limit_ratio", "dimension": "exit", "type": "float", "description": "Percentage of sells that are limit orders"},
    {"name": "exit_avg_gain_pct", "dimension": "exit", "type": "float", "description": "Mean return on winning closes"},
    {"name": "exit_avg_loss_pct", "dimension": "exit", "type": "float", "description": "Mean return on losing closes"},
    {"name": "exit_profit_target_cluster", "dimension": "exit", "type": "float", "description": "Std dev of gain% for winners (low = consistent target)"},
    {"name": "exit_stop_loss_cluster", "dimension": "exit", "type": "float", "description": "Std dev of loss% for losers (low = consistent stop)"},
    {"name": "exit_stop_tightness", "dimension": "exit", "type": "float", "description": "Median loss% on losing trades"},
    {"name": "exit_trailing_stop_score", "dimension": "exit", "type": "float", "description": "Percentage of winners exiting 5-15% below max gain"},
    {"name": "exit_at_high_of_day", "dimension": "exit", "type": "float", "description": "Percentage of sells in top 20% of day's range"},
    {"name": "exit_panic_score", "dimension": "exit", "type": "float", "description": "Percentage of sells on days stock drops 3%+"},
    {"name": "exit_take_profit_discipline", "dimension": "exit", "type": "float", "description": "Consistency of gain% on winning exits"},
    {"name": "exit_time_based", "dimension": "exit", "type": "float", "description": "Percentage of exits not explained by price target or stop"},
    {"name": "exit_partial_ratio", "dimension": "exit", "type": "float", "description": "Percentage of sells that reduce but don't close position"},
    {"name": "exit_full_ratio", "dimension": "exit", "type": "float", "description": "Percentage of sells that close entire position"},
    {"name": "exit_into_strength", "dimension": "exit", "type": "float", "description": "Percentage of sells on green stock days"},
    {"name": "exit_into_weakness", "dimension": "exit", "type": "float", "description": "Percentage of sells on red stock days"},
    {"name": "exit_after_earnings", "dimension": "exit", "type": "float", "description": "Percentage of sells within 5 days of likely earnings"},

    # ─── f06: Win/Loss Psychology (20) ──────────────────────────────────
    {"name": "psych_win_rate", "dimension": "psych", "type": "float", "description": "Percentage of closed positions profitable"},
    {"name": "psych_avg_win_usd", "dimension": "psych", "type": "float", "description": "Mean dollar gain on winners"},
    {"name": "psych_avg_loss_usd", "dimension": "psych", "type": "float", "description": "Mean dollar loss on losers"},
    {"name": "psych_win_loss_ratio", "dimension": "psych", "type": "float", "description": "Average win / average loss (absolute values)"},
    {"name": "psych_profit_factor", "dimension": "psych", "type": "float", "description": "Total gains / total losses"},
    {"name": "psych_expectancy", "dimension": "psych", "type": "float", "description": "(win_rate * avg_win) - (loss_rate * avg_loss) in USD"},
    {"name": "psych_max_consecutive_wins", "dimension": "psych", "type": "int", "description": "Longest winning streak"},
    {"name": "psych_max_consecutive_losses", "dimension": "psych", "type": "int", "description": "Longest losing streak"},
    {"name": "psych_behavior_after_3_wins", "dimension": "psych", "type": "float", "description": "Sizing change ratio after 3+ consecutive wins"},
    {"name": "psych_behavior_after_3_losses", "dimension": "psych", "type": "float", "description": "Sizing change ratio after 3+ consecutive losses"},
    {"name": "psych_revenge_score", "dimension": "psych", "type": "float", "description": "% of top-quartile losses followed by larger trade within 2 days"},
    {"name": "psych_freeze_score", "dimension": "psych", "type": "float", "description": "% of top-quartile losses followed by 7+ day inactivity"},
    {"name": "psych_loss_rebuy_rate", "dimension": "psych", "type": "float", "description": "% of losing closes where same ticker rebought within 30 days"},
    {"name": "psych_sunk_cost_score", "dimension": "psych", "type": "float", "description": "Correlation between loss magnitude and hold duration"},
    {"name": "psych_breakeven_exit_rate", "dimension": "psych", "type": "float", "description": "% of exits within +/- 2% of cost basis"},
    {"name": "psych_escalation", "dimension": "psych", "type": "float", "description": "% of losing positions where more was bought"},
    {"name": "psych_cutting_winners", "dimension": "psych", "type": "float", "description": "Average (exit gain / max unrealized gain) for winners"},
    {"name": "psych_letting_losers_run", "dimension": "psych", "type": "float", "description": "Average (exit loss / max unrealized loss) for losers"},
    {"name": "psych_emotional_index", "dimension": "psych", "type": "float", "description": "Composite of revenge, freeze, and streak sensitivity"},
    {"name": "psych_tilt_score", "dimension": "psych", "type": "float", "description": "Behavioral deviation during/after 15%+ drawdown"},

    # ─── f07: Instrument Sophistication (14) ────────────────────────────
    {"name": "instrument_unique_tickers", "dimension": "instrument", "type": "int", "description": "Total unique tickers traded"},
    {"name": "instrument_tickers_per_month", "dimension": "instrument", "type": "float", "description": "Average new tickers per active month"},
    {"name": "instrument_top1_concentration", "dimension": "instrument", "type": "float", "description": "% of trade value in most traded ticker"},
    {"name": "instrument_top3_concentration", "dimension": "instrument", "type": "float", "description": "% of trade value in top 3 tickers"},
    {"name": "instrument_etf_pct", "dimension": "instrument", "type": "float", "description": "% of trade value in ETFs"},
    {"name": "instrument_etf_as_core", "dimension": "instrument", "type": "int", "description": "1 if ETF allocation > 40%, 0 otherwise"},
    {"name": "instrument_options_pct", "dimension": "instrument", "type": "float", "description": "% of trades that are options"},
    {"name": "instrument_options_direction", "dimension": "instrument", "type": "int", "description": "1=calls only, -1=puts only, 0=both, null=no options"},
    {"name": "instrument_options_moneyness", "dimension": "instrument", "type": "float", "description": "Average (strike/spot) on options trades"},
    {"name": "instrument_options_avg_dte", "dimension": "instrument", "type": "float", "description": "Average days to expiry on options"},
    {"name": "instrument_leveraged_etf", "dimension": "instrument", "type": "int", "description": "Any leveraged ETF usage (1/0)"},
    {"name": "instrument_inverse_etf", "dimension": "instrument", "type": "int", "description": "Any inverse ETF usage (1/0)"},
    {"name": "instrument_sector_etf", "dimension": "instrument", "type": "int", "description": "Any sector ETF usage (1/0)"},
    {"name": "instrument_complexity_trend", "dimension": "instrument", "type": "float", "description": "Slope of instrument diversity over time"},

    # ─── f08: Sector & Ticker Behavior (18) ─────────────────────────────
    {"name": "sector_dominant", "dimension": "sector", "type": "int", "description": "Sector with most dollar volume (int encoded)"},
    {"name": "sector_count", "dimension": "sector", "type": "int", "description": "Number of unique sectors traded"},
    {"name": "sector_hhi", "dimension": "sector", "type": "float", "description": "Herfindahl concentration index"},
    {"name": "sector_rotation_frequency", "dimension": "sector", "type": "float", "description": "How often dominant sector changes per quarter"},
    {"name": "sector_tech_overweight", "dimension": "sector", "type": "float", "description": "Tech allocation % minus 30% market weight"},
    {"name": "sector_healthcare_pct", "dimension": "sector", "type": "float", "description": "Healthcare allocation percentage"},
    {"name": "sector_energy_pct", "dimension": "sector", "type": "float", "description": "Energy allocation percentage"},
    {"name": "sector_financial_pct", "dimension": "sector", "type": "float", "description": "Financials allocation percentage"},
    {"name": "sector_meme_exposure", "dimension": "sector", "type": "float", "description": "% of trades in known meme stocks"},
    {"name": "sector_mega_cap_pct", "dimension": "sector", "type": "float", "description": "% in top 10 S&P500 by market cap"},
    {"name": "sector_small_cap_score", "dimension": "sector", "type": "float", "description": "% in small cap stocks"},
    {"name": "sector_ipo_chaser", "dimension": "sector", "type": "int", "description": "Trades in recently IPO'd stocks (1/0)"},
    {"name": "sector_familiar_loyalty", "dimension": "sector", "type": "float", "description": "Concentration in top 1-2 sectors"},
    {"name": "sector_ticker_loyalty", "dimension": "sector", "type": "float", "description": "Average times same ticker is traded"},
    {"name": "sector_one_and_done_rate", "dimension": "sector", "type": "float", "description": "% of tickers traded exactly once"},
    {"name": "sector_core_vs_explore", "dimension": "sector", "type": "float", "description": "Top 5 tickers as % of all trades"},
    {"name": "sector_new_ticker_monthly_rate", "dimension": "sector", "type": "float", "description": "New tickers per month"},
    {"name": "sector_ticker_churn", "dimension": "sector", "type": "float", "description": "Month-over-month turnover of active tickers"},

    # ─── f09: Portfolio Construction (12) ───────────────────────────────
    {"name": "portfolio_avg_positions", "dimension": "portfolio", "type": "float", "description": "Average concurrent open positions"},
    {"name": "portfolio_max_positions", "dimension": "portfolio", "type": "int", "description": "Peak concurrent open positions"},
    {"name": "portfolio_monthly_turnover", "dimension": "portfolio", "type": "float", "description": "Monthly value traded / portfolio value"},
    {"name": "portfolio_diversification", "dimension": "portfolio", "type": "float", "description": "1 - HHI of holdings"},
    {"name": "portfolio_correlation", "dimension": "portfolio", "type": "float", "description": "Average pairwise correlation of held tickers"},
    {"name": "portfolio_long_only", "dimension": "portfolio", "type": "int", "description": "1 if never uses inverse/short, 0 if hedges"},
    {"name": "portfolio_cash_avg_pct", "dimension": "portfolio", "type": "float", "description": "Estimated average cash level"},
    {"name": "portfolio_max_drawdown", "dimension": "portfolio", "type": "float", "description": "Worst peak-to-trough estimated"},
    {"name": "portfolio_drawdown_recovery_days", "dimension": "portfolio", "type": "int", "description": "Days to recover from max drawdown"},
    {"name": "portfolio_income_component", "dimension": "portfolio", "type": "int", "description": "Any utility/REIT/dividend holdings (1/0)"},
    {"name": "portfolio_growth_vs_value", "dimension": "portfolio", "type": "float", "description": "Tilt: growth=1, value=-1"},
    {"name": "portfolio_beta_estimate", "dimension": "portfolio", "type": "float", "description": "Estimated beta vs SPY"},

    # ─── f10: Market Awareness (14) ─────────────────────────────────────
    {"name": "market_spy_trade_correlation", "dimension": "market", "type": "float", "description": "Correlation between SPY abs return and trade count"},
    {"name": "market_buys_on_dips", "dimension": "market", "type": "float", "description": "% of buys on SPY down 1%+ days"},
    {"name": "market_sells_on_dips", "dimension": "market", "type": "float", "description": "% of sells on SPY down 1%+ days"},
    {"name": "market_contrarian_score", "dimension": "market", "type": "float", "description": "(buys on dips - sells on dips) / total"},
    {"name": "market_herd_score", "dimension": "market", "type": "float", "description": "(buys on rallies - sells on rallies) / total"},
    {"name": "market_vix_sensitivity", "dimension": "market", "type": "float", "description": "Correlation between VIX level and activity"},
    {"name": "market_regime_adaptation", "dimension": "market", "type": "float", "description": "Behavior diff in bull vs bear regimes"},
    {"name": "market_fed_day_activity", "dimension": "market", "type": "float", "description": "Activity on FOMC dates vs normal"},
    {"name": "market_cpi_day_activity", "dimension": "market", "type": "float", "description": "Activity on CPI dates vs normal"},
    {"name": "market_earnings_season", "dimension": "market", "type": "float", "description": "Activity in earnings months vs others"},
    {"name": "market_sector_momentum", "dimension": "market", "type": "float", "description": "Buy sectors with positive momentum"},
    {"name": "market_relative_strength", "dimension": "market", "type": "float", "description": "Buy stocks outperforming sector"},
    {"name": "market_timing_success", "dimension": "market", "type": "float", "description": "SPY percentile rank on buy dates (low = good)"},
    {"name": "market_retail_correlation", "dimension": "market", "type": "float", "description": "Similarity to common retail patterns"},

    # ─── f11: Risk Management (14) ──────────────────────────────────────
    {"name": "risk_has_stops", "dimension": "risk", "type": "int", "description": "Evidence of consistent stop loss usage (1/0)"},
    {"name": "risk_avg_stop_distance", "dimension": "risk", "type": "float", "description": "Typical loss% at exit for losing trades"},
    {"name": "risk_max_loss_pct", "dimension": "risk", "type": "float", "description": "Biggest single loss return %"},
    {"name": "risk_max_position_risk", "dimension": "risk", "type": "float", "description": "Largest position * typical stop distance"},
    {"name": "risk_per_trade_consistency", "dimension": "risk", "type": "float", "description": "CV of dollar risk per trade"},
    {"name": "risk_hedge_ratio", "dimension": "risk", "type": "float", "description": "% of value in puts/inverse at any point"},
    {"name": "risk_sector_diversification", "dimension": "risk", "type": "float", "description": "1 - sector HHI"},
    {"name": "risk_trim_winners", "dimension": "risk", "type": "float", "description": "% of partial closes on winning positions"},
    {"name": "risk_increase_trend", "dimension": "risk", "type": "float", "description": "Slope of avg position risk over time"},
    {"name": "risk_adjusted_return", "dimension": "risk", "type": "float", "description": "Total return / stdev of trade returns"},
    {"name": "risk_worst_week", "dimension": "risk", "type": "float", "description": "Return during worst calendar week"},
    {"name": "risk_recovery_after_worst", "dimension": "risk", "type": "float", "description": "Sizing change after worst week vs normal"},
    {"name": "risk_max_leverage", "dimension": "risk", "type": "int", "description": "Max leveraged product usage (1/2/3x)"},
    {"name": "risk_evolution", "dimension": "risk", "type": "float", "description": "Risk management improvement over time"},

    # ─── f12: Behavioral Biases (12) ────────────────────────────────────
    {"name": "bias_disposition", "dimension": "bias", "type": "float", "description": "Holding disposition ratio (losers/winners hold time)"},
    {"name": "bias_anchoring", "dimension": "bias", "type": "float", "description": "% of rebuys within 3% of previous buy price"},
    {"name": "bias_recency", "dimension": "bias", "type": "float", "description": "Correlation between recent return and rebuy probability"},
    {"name": "bias_familiarity", "dimension": "bias", "type": "float", "description": "Sector HHI (concentration = familiarity bias)"},
    {"name": "bias_action", "dimension": "bias", "type": "float", "description": "Total trades per month (overtrading measure)"},
    {"name": "bias_status_quo", "dimension": "bias", "type": "float", "description": "1 - monthly turnover rate"},
    {"name": "bias_denomination", "dimension": "bias", "type": "float", "description": "Average stock price traded"},
    {"name": "bias_round_number", "dimension": "bias", "type": "float", "description": "% of entries/exits at round dollar prices"},
    {"name": "bias_confirmation", "dimension": "bias", "type": "float", "description": "% of losing positions where more was bought"},
    {"name": "bias_endowment", "dimension": "bias", "type": "float", "description": "Avg hold on losers vs winners ratio"},
    {"name": "bias_availability", "dimension": "bias", "type": "float", "description": "% of trades in top-20 most-traded stocks"},
    {"name": "bias_overconfidence", "dimension": "bias", "type": "float", "description": "Composite of sizing after wins + new tickers after wins"},

    # ─── f13: Social & Trend Sensitivity (10) ──────────────────────────
    {"name": "social_meme_rate", "dimension": "social", "type": "float", "description": "% of trades in meme stock list"},
    {"name": "social_trend_entry_speed", "dimension": "social", "type": "float", "description": "Days from data start to first meme stock entry"},
    {"name": "social_trend_exit_timing", "dimension": "social", "type": "float", "description": "Meme position avg return normalized to [-1,1]"},
    {"name": "social_earnings_reaction_speed", "dimension": "social", "type": "float", "description": "Hours after earnings to trade (daily data = null)"},
    {"name": "social_news_driven_estimate", "dimension": "social", "type": "float", "description": "% of trades on high volume days"},
    {"name": "social_copycat", "dimension": "social", "type": "float", "description": "Jaccard similarity to top retail stocks"},
    {"name": "social_contrarian_independence", "dimension": "social", "type": "float", "description": "1 - meme_rate (independence from trends)"},
    {"name": "social_hype_position", "dimension": "social", "type": "float", "description": "Entry timing in hype cycles (early/mid/late)"},
    {"name": "social_bagholding", "dimension": "social", "type": "float", "description": "% of meme positions still held 30+ days after open"},
    {"name": "social_influence_trend", "dimension": "social", "type": "float", "description": "Slope of meme exposure over time"},

    # ─── f14: Learning & Adaptation (10) ────────────────────────────────
    {"name": "learning_win_rate_trend", "dimension": "learning", "type": "float", "description": "Win rate improvement (2nd half - 1st half)"},
    {"name": "learning_return_trend", "dimension": "learning", "type": "float", "description": "Average return improvement"},
    {"name": "learning_risk_trend", "dimension": "learning", "type": "float", "description": "Average loss size change (negative = improving)"},
    {"name": "learning_hold_optimization", "dimension": "learning", "type": "float", "description": "Hold period CV change (negative = more consistent)"},
    {"name": "learning_mistake_repetition", "dimension": "learning", "type": "float", "description": "% of losing tickers rebought and losing again"},
    {"name": "learning_sizing_improvement", "dimension": "learning", "type": "float", "description": "Sizing CV change (negative = more systematic)"},
    {"name": "learning_new_strategy", "dimension": "learning", "type": "float", "description": "Change in instrument mix"},
    {"name": "learning_recovery_improvement", "dimension": "learning", "type": "float", "description": "Drawdown recovery speed change"},
    {"name": "learning_loss_cutting", "dimension": "learning", "type": "float", "description": "Change in avg loss hold duration"},
    {"name": "learning_skill_trajectory", "dimension": "learning", "type": "float", "description": "Composite learning score (positive = improving)"},

    # ─── f15: Unique Signature (8) ──────────────────────────────────────
    {"name": "sig_favorite_devotion", "dimension": "sig", "type": "float", "description": "Trades in #1 ticker / total trades"},
    {"name": "sig_recurring_dates", "dimension": "sig", "type": "int", "description": "Date patterns repeating monthly or biweekly (1/0)"},
    {"name": "sig_payday_pattern", "dimension": "sig", "type": "float", "description": "Trade clustering at ~14 or ~30 day intervals"},
    {"name": "sig_seasonal_score", "dimension": "sig", "type": "float", "description": "Max monthly activity / min monthly activity"},
    {"name": "sig_preferred_hold", "dimension": "sig", "type": "int", "description": "Mode hold bucket (0=day, 1=swing, 2=position, 3=investment)"},
    {"name": "sig_portfolio_reset", "dimension": "sig", "type": "int", "description": "Ever sold 80%+ positions in a week (1/0)"},
    {"name": "sig_strategy_drift", "dimension": "sig", "type": "float", "description": "Euclidean distance between first and last quarter features"},
    {"name": "sig_uniqueness", "dimension": "sig", "type": "float", "description": "Mahalanobis distance from centroid (null for single trader)"},
]


def get_schema() -> list[dict]:
    """Return the full feature schema."""
    return FEATURE_SCHEMA


def get_schema_summary() -> dict:
    """Return summary stats about the schema."""
    dimensions: dict[str, int] = {}
    for f in FEATURE_SCHEMA:
        dim = f["dimension"]
        dimensions[dim] = dimensions.get(dim, 0) + 1
    return {
        "total_features": len(FEATURE_SCHEMA),
        "dimensions": dimensions,
        "dimension_count": len(dimensions),
    }
