-- Parser configs table for the Universal Self-Learning Trade Ingestion System.
-- Stores reusable parser configurations generated by Claude or seeded manually.
-- Each config maps a CSV header signature to column mappings and action maps.

CREATE TABLE IF NOT EXISTS parser_configs (
    config_id       TEXT PRIMARY KEY,
    format_name     TEXT NOT NULL DEFAULT '',
    header_signature TEXT NOT NULL,
    config_json     JSONB NOT NULL,
    source          TEXT NOT NULL DEFAULT 'seed',   -- 'seed', 'claude', 'manual'
    confidence      REAL NOT NULL DEFAULT 1.0,
    times_used      INTEGER NOT NULL DEFAULT 0,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index on header_signature for fast lookup
CREATE INDEX IF NOT EXISTS idx_parser_configs_signature
    ON parser_configs (header_signature);

-- Index on source for filtering
CREATE INDEX IF NOT EXISTS idx_parser_configs_source
    ON parser_configs (source);

-- Function to increment usage counter (called via RPC)
CREATE OR REPLACE FUNCTION increment_parser_config_usage(p_config_id TEXT)
RETURNS VOID AS $$
BEGIN
    UPDATE parser_configs
    SET times_used = times_used + 1,
        updated_at = now()
    WHERE config_id = p_config_id;
END;
$$ LANGUAGE plpgsql;

-- Enable RLS
ALTER TABLE parser_configs ENABLE ROW LEVEL SECURITY;

-- Allow service role full access
CREATE POLICY parser_configs_service_all
    ON parser_configs
    FOR ALL
    USING (true)
    WITH CHECK (true);
